# Generated by Django 5.1.2 on 2024-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
