# Generated by Django 5.1.2 on 2024-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0004_remove_savedwrap_minutes_listened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedwrap',
            name='favorite_decade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savedwrap',
            name='favorite_mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedwrap',
            name='peak_hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savedwrap',
            name='top_playlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
