# Generated by Django 5.1.2 on 2024-11-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0005_savedwrap_favorite_decade_savedwrap_favorite_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedwrap',
            name='top_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='savedwrap',
            name='top_tracks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
