# Generated by Django 5.1 on 2024-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0007_savedwrap_top_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedwrap',
            old_name='favorite_mood',
            new_name='top_song',
        ),
        migrations.RenameField(
            model_name='savedwrap',
            old_name='peak_hour',
            new_name='top_song_popularity',
        ),
        migrations.RemoveField(
            model_name='savedwrap',
            name='top_playlist',
        ),
        migrations.AddField(
            model_name='savedwrap',
            name='user_element',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
