# Generated by Django 5.1.2 on 2024-12-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0008_rename_favorite_mood_savedwrap_top_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedwrap',
            name='favorite_decade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedwrap',
            name='top_song_popularity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
