# Generated by Django 5.1.2 on 2024-12-02 03:08

from django.db import migrations
import json

def convert_top_album_to_json(apps, schema_editor):
    SavedWrap = apps.get_model('spotifywrapper', 'SavedWrap')
    for wrap in SavedWrap.objects.all():
        try:
            # Check if top_album is not already a dictionary (JSON)
            if wrap.top_album and isinstance(wrap.top_album, str):
                # Convert the string to a valid JSON object
                wrap.top_album = json.dumps({'name': wrap.top_album})
                wrap.save()
        except Exception as e:
            print(f"Error converting top_album for wrap {wrap.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0009_alter_savedwrap_favorite_decade_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_top_album_to_json),
    ]
