# Generated by Django 5.1.2 on 2024-12-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapper', '0010_update_top_album_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedwrap',
            name='top_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
